# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

branches:
  only:
    - master
    - 6.0

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y ninja-build cppcheck doxygen help2man texlive graphviz libqt4-dev qt4-qmake
  - wget --no-check-certificate http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - export CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2"
  - export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH   

script:
  # Test using GNU make
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON ..
  - make -j4
  - make doc
  - cd ..
  - rm -rf build
  # Test using ninja (build system)
  - mkdir build
  - cd build
  - cmake -GNinja -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON ..
  - ninja
  - ninja doc
  - ninja test
  - cd ..
  - rm -rf build
  # Test using cppcheck (static code analysis)
  - cppcheck . --error-exitcode=1 -iexamples/cpp/prev_prime.cpp -iexamples/cpp/primesieve_iterator.cpp
  # Build primesieve GUI app
  - cd src/gui
  - qmake 
  - make -j4
