# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

branches:
  only:
    - master
    - 6.0

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y cppcheck doxygen help2man texlive graphviz
  - wget --no-check-certificate http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - export CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2"
  - export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH   

script:
  - cmake -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON .
  - make
  - make doc
  - make test
  - cppcheck . --error-exitcode=1 -iCMakeFiles -icmake-3.1.3-Linux-x86_64 -iexamples/cpp/previous_prime.cpp -iexamples/cpp/primesieve_iterator.cpp
