# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y cppcheck help2man
  - wget --no-check-certificate http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - export CXX="g++-4.8" CC="gcc-4.8";
  - export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH;   

script:
  - cmake .
  - make VERBOSE=1
  - ./primesieve --test
