# Test configuration for Travis CI. See <https://travis-ci.org/>.
language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - OMP_NUM_THREADS=4

install:
  - sudo apt-get install -y cppcheck help2man

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-examples --enable-maintainer-mode CXXFLAGS="-Wall -Wextra -Werror -Wno-long-long -pedantic -O2"
  - make
  - sudo make install
  - make dist
  - make distcheck
  - cppcheck . --error-exitcode=1 -iexamples/cpp/previous_prime.cpp -iexamples/cpp/primesieve_iterator.cpp
