# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Previous Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug

build_script:
  - cmake -G "NMake Makefiles" .
  - nmake

test_script:
  - ctest
