# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  only:
  - master
  - 6.0

configuration:
  - Debug

os: Visual Studio 2015

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" .
  - cmake --build .

test_script:
  - ctest
