# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  only:
  - master
  - 6.0

configuration:
  - Debug

environment:
  matrix:
  - cmake_generator: "Visual Studio 14"
    platform: x86
  - cmake_generator: "Visual Studio 14 Win64"
    platform: x64

before_build:
  - "\"C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Bin\\SetEnv.cmd\" /%platform%"
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %platform%"

build_script:
  - cmake -G "%cmake_generator%" .
  - cmake --build .

test_script:
  - ctest
