# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

image:
- Ubuntu
- macos
- Visual Studio 2019

branches:
  except:
    - gh-pages

platform:
  - x64

configuration:
  - Debug
  - Release

for:
  - matrix:
      only:
        - image: Ubuntu
          platform: x64
          configuration: Debug
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long -O1 -g -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer"
    build_script:
      - cmake . -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=$Configuration
      - make VERBOSE=1
    test_script:
      - ctest

  - matrix:
      only:
        - image: Ubuntu
          platform: x64
          configuration: Release
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long"
    build_script:
      - cmake . -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$Configuration
      - make VERBOSE=1
    test_script:
      - ctest

  - matrix:
      only:
        - image: macos
          platform: x64
    environment:
      CFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long"
      CXXFLAGS: "-Wall -Wextra -pedantic -Werror -Wno-long-long"
    build_script:
      - cmake . -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$Configuration
      - make VERBOSE=1
    test_script:
      - ctest

  - matrix:
      only:
        - image: Visual Studio 2019
          platform: x64
    environment:
      CFLAGS: "/W3 /WX"
      CXXFLAGS: "/W3 /WX"
    build_script:
      - cmake . -G "Visual Studio 16 2019" -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=%Configuration%
      - cmake --build . --config %Configuration% --target install
    test_script:
      - ctest -C %Configuration%
