# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2017

platform:
  - x86
  - x64

build_script:
  - if "%platform%" == "x86" cmake -G "Visual Studio 15 2017" -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON .
  - if "%platform%" == "x64" CXXFLAGS="/W4 /WX" cmake -G "Visual Studio 15 2017 Win64" -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON .
  - cmake --build .

test_script:
  - ctest -C Debug
