# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

build_script:
  - cmake -G "Visual Studio 14 2015 Win64" .
  - cmake --build .

test_script:
  - ctest
