# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2017 RC

platform:
  - x64

build_script:
  - cmake -G "Visual Studio 15 2017 Win64" .
  - cmake --build .

test_script:
  - ctest
